files:
    model_weights_path: <path to yolo weights> 
    model_config_path: <path to model config file>
    coco_names: <path to coco names file>
image: 
    size: [416, 416]
    scalefactor: 0.00392
    mean: [0, 0, 0]
    swapRB: True
thresholds:
    score_threshold: 0.5
    nms_threshold: 0.4
    conf_threshold: 0.3
utils:
    write_perf_information: True
    skip_frames: 1 # set 1 for no skipping otherwise positive number. 
    max_distance: 300
    is_on_rails_distance: 100
    line: [0, 700, 1100, 500]
    use_opencv: True
log:
    filename: <log filename> 
    level: <log level>
backend: 
    inference_engine: False #if you are not using NCS (Neural Compute Stick), set this property to False
trakcer: 
    use_tracker: True
    timestamp_init_frames: 10
    multi_tracker: True
    trakcer_type: <tracker type>
